version: '2'

services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./data/sample.yml:/usr/share/nginx/html/sample.yml
    environment:
      API_URL: sample.yml
    ports:
      - "8001:8080"
