version: '3'

services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - '9000:80'
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/www:/var/www/html
