version: '3'

services:
  node_express:
    image: node:10.4.0-alpine
    container_name: node_express
    hostname: node_express
    volumes:
      - "/node_project:/src"
    working_dir: /src
    command: [sh, -c, npm install && npm start]
    ports:
      - "3001:3000"
