version: '3'

services:
  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: development
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
    volumes:
      - ./data/mysql:/var/lib/mysql
